# Generated by Django 2.1.2 on 2019-01-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(null=True)),
                ('rg', models.CharField(max_length=20, null=True)),
                ('estado_civil', models.IntegerField(choices=[(1, 'Casado'), (2, 'Divorciado'), (3, 'Desquitado'), (4, 'Não Informado'), (5, 'Outro'), (6, 'Separado'), (7, 'Solteiro'), (8, 'Viúvo')], default=4)),
                ('nome_conjuge', models.CharField(max_length=100, null=True)),
                ('data_nascimento', models.CharField(max_length=10)),
                ('nome_mae', models.CharField(max_length=100, null=True)),
                ('nome_pai', models.CharField(max_length=100, null=True)),
                ('fixo', models.CharField(max_length=15, null=True)),
                ('celular', models.CharField(max_length=15, null=True)),
                ('zap', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('escolaridade', models.IntegerField(choices=[(1, 'Bacharel'), (2, 'Fundamental Completo'), (3, 'Fundamental Incompleto'), (4, 'Médio Completo'), (5, 'Médio Incompleto'), (6, 'Não Informado'), (7, 'Pós Graduado'), (8, 'Superior Completo'), (9, 'Superior Incompleto')], default=6, null=True)),
                ('recebimento', models.IntegerField(choices=[(1, 'Carta'), (2, 'Batismo'), (3, 'Aclamação')], default=1, null=True)),
                ('cargo', models.IntegerField(choices=[(1, 'Auxiliar'), (2, 'Diácono'), (3, 'Prebítero'), (4, 'Evangelista'), (5, 'Pastor')], default=1, null=True)),
                ('solicitar_credencial', models.BooleanField(default=False)),
                ('data_batismo_aguas', models.CharField(max_length=10, null=True)),
                ('data_batismo_es', models.CharField(max_length=10, null=True)),
                ('departamento', models.CharField(max_length=50, null=True)),
                ('endereco_igreja', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=4)),
                ('naturalidade', models.CharField(max_length=20, null=True)),
                ('uf_naturalidade', models.CharField(max_length=2, null=True)),
                ('nacionalidade', models.CharField(max_length=20, null=True)),
                ('data_consagracao', models.CharField(max_length=10, null=True)),
                ('curso_teologico', models.IntegerField(choices=[(1, 'Bacharel'), (2, 'Básico'), (3, 'Médio')], default=3)),
                ('convencao_origem', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
