# Generated by Django 2.1.2 on 2019-01-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='curso_teologico',
            field=models.IntegerField(choices=[(1, 'Bacharel'), (2, 'Básico'), (3, 'Médio')], default=3, null=True),
        ),
    ]
